@startuml
:スタート;
if (本社所属ないしは国内出向中の従業員の申請である) then (はい)
  :申請経路妥当性チェックへ;
  note left
    上司印が押下されているか確認
  end note
  fork
    :新経路が電車もしくはバスを使用する場合;
    if(以下の会社至近要件のいずれかに該当しない
    ①自宅→会社までの徒歩通勤距離>1km
    ②至近駅が出発駅となっている) then (はい)
    note left
     至近駅は以下の通り。
     荒川線「小台」～「町屋二丁目」
     舎人ライナー「足立小台」～「赤土小学校前」
    end note
    else (いいえ)
    :会社至近により交通費支給なし;
    :差戻;
    detach
    endif
    if(住所から適切な最寄駅・バス停を出発駅としているか) then(はい)
    note right
     最寄駅・バス停チェックにはGoogle Mapを使用
     (日本は地図サービスにおいて
     バス停情報が充実していないので要注意)
    endnote
    else(いいえ)
    :差戻;
    detach
    endif
    if (自宅最寄り駅までのバス使用なし) then (はい)
    else (いいえ)
      if(以下のバス使用許可要件を両方満たしているかチェック
      ①自宅から最寄り駅までの徒歩距離>1km
      ②バス乗車距離>1km)
      note left
         右記のバス使用許可要件について見直し？
         ・最寄りバス停からのバスが最寄り駅に行かない経路
        end note
      else (いいえ)
      :最寄り駅を始発とする経路に修正;
      :差戻;
      detach
      endif
    endif
    :電車経路妥当性チェックへ;
    note right
     最終的に「最安経路」「最速経路」
     「最速経路より安いすべての経路」
     のどれかに該当しない場合は×としたい
     end note
    if(最安経路である)then(はい)
    :経路確定;
    else(いいえ)
     if (最安経路でない理由が以下のどれかに該当する
     ①申請経路より安い経路が全て途中でバスを使用する
     ②特例経路に該当している)then(はい)
     note left
      最安経路ではあるが特例経路を使用することで
      早い経路を使用できる場合は、一応その旨を確認
     end note
     :経路確定;
     else(いいえ)
     :申請経路の妥当性について個別判断を行う;
     note right
      この個別判断をなくしたい
     end note
     endif
    endif
    :確定経路についてCOMPANYに登録;
    note left
    同じ期で2回目の通勤経路変更の場合に注意
    end note
  fork again
    :新経路が徒歩のみの場合;
    :旧経路の払い戻しがあれば実行
    ====
    新経路（徒歩）については処理なし;
    note right
     将来的にCOMPNAYにおいては
     「徒歩のみ」の登録を行えるように調整中
     （現時点では徒歩のみで登録すると
     　毎月通勤交通費データに上がってきてしまい利便性×）
    end note
  endfork
elseif (労務管理部署がある事業所所属の従業員である
対象：大阪、鹿島、千葉、明石、浦和、三重、
　　　久喜、相馬、富士) then (はい)
  :上司印およびが労務管理部署長印が押下されているか確認;
  :原則的に経路チェックは各事業所が担当するが、
  余裕があれば本社でもチェックを行う
  （特に尾久は本社と同じ基準を使用しているので
  　経路チェックだけでも行うとよい）;
else (いいえ)
  :労務管理部署が存在しない事業所の申請については
  上司印が押下されていることを確認
  経路判断は一応行うがほぼ最安経路の申請
  ====
  対象：札幌、仙台、名古屋、福岡;
  :申請経路をCOMPANYに登録、本社で確認;
endif
:交通費サブシステムにおける計算処理;
:給与計算処理;
:交通費データを各事業所労務管理部署に送付;
note right
 給与計算3日目までに修正を行うように指示。
 給与計算3日目のデータ送付時は修正する際に人事部まで至急連絡する
end note
:入力に修正があれば対応;
:給与確定後、交通費サブシステムの〆処理を実行;
:通勤交通費申請書に人事・健康管理GL印を押下し、ファイリングする;
:終了;

@enduml
