@startuml
:スタート;
:各事業所・部署から届いた扶養控除異動申告書をファイリング;
note right
  昨年までは事業所ごとにファイル分けしていたが、
  あまり意味がないと思うので連番順に250枚/冊でファイリング
endnote
fork
  :連番データをもとに提出状況を確認、抜け・漏れをチェック
  ====
  連番データ所在：共有F＞年末調整＞各種申告書＞扶養控除異動申告書;
  note right
    提出不要者：①退職者で2019年に給与支払いがない人、
    ②外部取締役（乙欄）③大阪・芝氏（乙欄）④海外出向者
  endnote
  :原則的に1月給与支給日までに全員提出、
  最悪扶養手当の対応が間に合う2月給与計算時までに全員提出;
fork again
  :扶養控除異動申告書の提出内容をもとに個人情報の修正を行う
 【COMPNAY起動経路】個人情報エクスプローラ;
  note right
    昨年までは扶養控除異動申告書にマイナンバーが記載されている可能性が
    あったため、給与担当者のみで対応を行っていたが、
    今年のフォーマットからマイナンバーの記入を不要としたので
    非給与担当者にも仕事を振っても良いかもしれない
  endnote
  fork
  :家族情報修正対応;
  note right
    昨年と異なり、家族情報は予め印字された状態で従業員に配布されている
  endnote
    fork
    :扶養親族追加対応
    ====
    申告書に手書きで家族情報が追記されている;
    :【COMPANY】個人情報エクスプローラ＞家族から現在の登録状況を確認;
      if(既に該当家族が登録済みである)then(はい)
        if(該当家族が配偶者である)then(はい)
          if(「控除区分」項目が「控除あり」である)then(はい)
          :「従業員自身が高所得者であるため、
          配偶者を源泉控除対象配偶者にできないが、
          配偶者の年収は103万円以下であるため扶養親族ではある」
          という状態なので処理不要;
          else(いいえ)
          :「履歴適用日付」を「2019年1月1日」にした上で
          控除区分を「控除あり」に変更;
          :扶養手当の支給は2月からになるので扶養手当人数調整処理が必要;
          :「扶養増」の付箋を立てる;
          endif
        else(いいえ)
            if(「控除区分」項目が「控除あり」である)then(はい)
            :このケースが発生した場合は田邉に即時報告;
            else(いいえ)
            :「履歴適用日付」を「2019年1月1日」にした上で
            控除区分を「控除あり」に変更;
            :扶養手当の支給は2月からになるので扶養手当人数調整処理が必要;
            :「扶養増」の付箋を立てる;
            endif
        endif
      else(いいえ)
      :該当家族の登録処理
      ====
      「履歴適用日付」を「2019年1月1日」にして
      「家族」→「追加」、氏名、生年月日、同局区分、障害情報、住所情報を入力;
      note right
          「所得の見積額」＞38万円だった場合は予想年収について要確認
      endnote
      :「扶養増」の付箋を立てる;
      endif
    fork again
    :扶養親族外し対応
    ====
    申告書に印字されている家族情報が二重線で消されている;
    :【COMPANY】個人情報エクスプローラ＞家族から現在の登録状況を確認;
    :「履歴適用日付」を2019年1月1日にして「控除区分」を「控除なし」に変更」;
    :「扶養減」の付箋を立てる;
      if(「異動事由」欄に「就職のため4/1から外し」のコメントがある)then(はい)
      :扶養手当を3月まで出す必要があるので、
      扶養手当人数調整処理が必要;
      else(いいえ)
      endif
    endfork
    fork again
    :配偶者情報更新対応;
    :配偶者情報の訂正がある場合は付箋を立てる;
    fork again
    :住所情報変更対応;
    :本人・家族に関する住所情報・世帯主情報に
    変更がある場合は付箋を立てる;
  endfork
:給与計算処理後、「扶養増」「扶養減」の付箋が立っている従業員の扶養手当について、
意図した金額が支給されていることを確認;
:終了;

@enduml
